In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r'C:\Users\spars\OneDrive\Desktop\senti\train.csv')
df.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [3]:
df.isnull().sum()

id       0
label    0
tweet    0
dtype: int64

In [4]:
X = df.drop(['label'],axis=1)
y = df['label']

In [5]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\spars\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\spars\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


In [6]:
lemmatizer = WordNetLemmatizer()
corpus = []
for i in range(len(df)):
  review = re.sub('[^a-zA-Z]',' ',df['tweet'][i])
  review = review.lower()
  review = review.split()
  review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)
corpus

['user father dysfunctional selfish drag kid dysfunction run',
 'user user thanks lyft credit use cause offer wheelchair van pdx disapointed getthanked',
 'bihday majesty',
 'model love u take u time ur',
 'factsguide society motivation',
 'huge fan fare big talking leave chaos pay dispute get allshowandnogo',
 'user camping tomorrow user user user user user user user danny',
 'next school year year exam think school exam hate imagine actorslife revolutionschool girl',
 'love land allin cavs champion cleveland clevelandcavaliers',
 'user user welcome gr',
 'ireland consumer price index mom climbed previous may blog silver gold forex',
 'selfish orlando standwithorlando pulseshooting orlandoshooting biggerproblems selfish heabreaking value love',
 'get see daddy today day gettingfed',
 'user cnn call michigan middle school build wall chant tcot',
 'comment australia opkillingbay seashepherd helpcovedolphins thecove helpcovedolphins',
 'ouch junior angry got junior yugyoem omg',
 'thankf

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=12000)
X = cv.fit_transform(corpus).toarray()

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=10)

In [9]:
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score,recall_score,classification_report
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)
log_pred=log_reg.predict(X_test)

print('Accuracy Score:{}'.format(accuracy_score(y_test, log_pred)))
print('Classification Report:')
print(classification_report(y_test,log_pred))

Accuracy Score:0.9581812493482115
Classification Report:
             precision    recall  f1-score   support

          0       0.96      0.99      0.98      8893
          1       0.87      0.50      0.63       696

avg / total       0.96      0.96      0.95      9589



In [12]:
cm_log = confusion_matrix(y_test,log_pred)
cm_log

array([[8840,   53],
       [ 348,  348]], dtype=int64)

In [13]:
from sklearn.tree import DecisionTreeClassifier
dst=DecisionTreeClassifier()
dst.fit(X_train,y_train)
dst_pred=dst.predict(X_test)
print('Accuracy Score:{}'.format(accuracy_score(y_test, dst_pred)))
print('Classification Report:')
print(classification_report(y_test,dst_pred))

Accuracy Score:0.9442069037438732
Classification Report:
             precision    recall  f1-score   support

          0       0.96      0.98      0.97      8893
          1       0.63      0.55      0.59       696

avg / total       0.94      0.94      0.94      9589



In [14]:
cm_dst = confusion_matrix(y_test,dst_pred)
cm_dst

array([[8674,  219],
       [ 316,  380]], dtype=int64)

In [16]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB().fit(X_train,y_train)
mnb_pred=mnb.predict(X_test)
print('Accuracy Score:{}'.format(accuracy_score(y_test, mnb_pred)))
print('Classification Report:')
print(classification_report(y_test,mnb_pred))

Accuracy Score:0.9471269162582125
Classification Report:
             precision    recall  f1-score   support

          0       0.97      0.97      0.97      8893
          1       0.63      0.66      0.64       696

avg / total       0.95      0.95      0.95      9589



In [18]:
cm_mnb = confusion_matrix(y_test,mnb_pred)
cm_mnb

array([[8624,  269],
       [ 238,  458]], dtype=int64)

In [17]:
from sklearn.ensemble import RandomForestClassifier
rmf=RandomForestClassifier(n_estimators=100)
rmf.fit(X_train,y_train)
rmf_pred=rmf.predict(X_test)
print('Accuracy Score:{}'.format(accuracy_score(y_test, rmf_pred)))
print('Classification Report:')
print(classification_report(y_test,rmf_pred))

Accuracy Score:0.9615184065074565
Classification Report:
             precision    recall  f1-score   support

          0       0.97      0.99      0.98      8893
          1       0.87      0.55      0.67       696

avg / total       0.96      0.96      0.96      9589



In [19]:
cm_rmf = confusion_matrix(y_test,rmf_pred)
cm_rmf

array([[8838,   55],
       [ 314,  382]], dtype=int64)